require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
source 'https://cdn.cocoapods.org'
require_relative '../node_modules/react-native/scripts/react_native_pods'

# From RNP docs here: https://www.npmjs.com/package/react-native-permissions/v/4.0.1
def node_require(script)
  # Resolve script with node to allow for hoisting
  require `node -p "require.resolve('#{script}', {paths: [process.argv[1]]})" #{__dir__}`.strip
end
  
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.0'
prepare_react_native_project!

# uncomment wanted permissions (also from RNP docs linked above)
setup_permissions([
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  'Camera',
  # 'Contacts',
  'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  'Microphone',  # Required for WebRTC video calls
  # 'Motion',
  'Notifications',  # Required for push notifications
  # 'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AriesBifold' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  # Firebase for push notifications
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  #permissions_path = '../node_modules/react-native-permissions/ios'
  #pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  #pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  # use reactNativePermissionsIOS.json for permissions instead!!!

  # Firebase for push notifications
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true


  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    #:flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AriesBifoldTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Fix CatCrypto module issue - add correct module map paths
    # to resolve "Unable to find module dependency: Argon2/MD6/SHA3" errors
    installer.pods_project.targets.each do |target|
      if ['CatCrypto', 'RNArgon2'].include?(target.name)
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_INCLUDE_PATHS'] = '$(inherited) "${PODS_ROOT}/CatCrypto/Sources/ModuleMaps/Argon2" "${PODS_ROOT}/CatCrypto/Sources/ModuleMaps/MD6" "${PODS_ROOT}/CatCrypto/Sources/ModuleMaps/SHA3"'
        end
      end

      # Fix swiftWebKit library not found error (Xcode 26+)
      # In Xcode 26, Apple removed separate swiftXXX libraries - they're now part of the frameworks
      target.build_configurations.each do |config|
        config.build_settings['LIBRARY_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['LIBRARY_SEARCH_PATHS'] << '$(SDKROOT)/usr/lib/swift'
        config.build_settings['LIBRARY_SEARCH_PATHS'] << '$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)'
        config.build_settings['LIBRARY_SEARCH_PATHS'] << '$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)'
      end
    end
  end
end